### ISSUE TITLE
初级前端，初级后端，初级xx,经常问的的一些煞笔问题

### ISSUE THREAD

**Issue by hfuuss** [hfuuss/blog#6]
【煞笔】：请问谁用过 vue-awesome-swiper 这个  帮忙解决一下问题， 谢谢~
> 就是sb，有人回复就怪了。

**Comment by hfuuss** [comment]
老哥问下webpack的插件为什么不会影响到devServer
我用了一个插件把文件防止在磁盘
查看磁盘文件已经被修改了，但是浏览器的文件没有正确被反应
> 瞎jb说，webpack的插件为什么不会影响到devServer，咋就不会了？你是不是没重启吧？或者浏览器有缓存等等。还将【放置】打错成【防止】。sb一个。
>正确文法：大佬们，我用了一个插件把文件放置在磁盘,查看磁盘文件已经被修改了，但是浏览器的文件没有正确被反应，用的是webpack-devServer，一般哪里会有问题呢？

**Comment by hfuuss** [comment]
![image](https://user-images.githubusercontent.com/14094844/57302744-78b32d00-710e-11e9-9596-cec46cd3e45d.png)
老哥们，为啥报错了呀？
> 完全是sb，浏览器都提示了`path is not defined`,自己去查path相关的定义就可以了。

**Comment by hfuuss** [comment]
https://github.com/reixs/reixs
求star
> sb,现在为啥会有人求star呢?点进去一看，网址是假的...唬人呢

**Comment by hfuuss** [comment]
【煞笔】：
![image](https://user-images.githubusercontent.com/14094844/57345460-7fc55400-717d-11e9-8554-6edf91064a4f.png)
这样的警告是什么
> sb...

**Comment by al1120877019** [comment]
哈哈哈
